### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by Smart-SangGe** [cpcloud/minesweep-rs#1241]
cargo run 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/minesweep`
thread 'main' panicked at src/ui.rs:405:45:
                                           attempt to subtract with overflow
                                                                            stack backtrace:
                                                                                               0:     0x564f91d056c5 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                                                                    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
                                       1:     0x564f91d056c5 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                                                                                                                                                                   at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
                                                                                                                               2:     0x564f91d056c5 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                                                                                            at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
                                           3:     0x564f91d056c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                                                   at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
                                                                                                                                                      4:     0x564f91d286fb - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                                                                                                         at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
                                             5:     0x564f91d286fb - core::fmt::write::hc090a2ffd6b28c4a
                                                                                                                                       at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
                                                                             6:     0x564f91d0340f - std::io::Write::write_fmt::h8898bac6ff039a23
                                                                                                                                                                                at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
                                                                                                                    7:     0x564f91d0549e - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                                                                             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
                            8:     0x564f91d0549e - std::sys_common::backtrace::print::ha96650907276675e
                                                                                                                                       at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
                                                                                      9:     0x564f91d06759 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
                         10:     0x564f91d0649d - std::panicking::default_hook::h207342be97478370
                                                                                                                                at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
                                                                    11:     0x564f91d06bf3 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                                at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:795:13
                                                                                                                        12:     0x564f91d06a9b - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                                                                                                at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:656:13
                                     13:     0x564f91d05b89 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                                                                                                                                                                      at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
                                                                                                                      14:     0x564f91d06807 - rust_begin_unwind
                                            at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
                                                                                                                                   15:     0x564f91ac0e23 - core::panicking::panic_fmt::hdc63834ffaaefae5
                                                                                     at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
                          16:     0x564f91ac1547 - core::panicking::panic_const::panic_const_sub_overflow::h425c3b698451930e
                                                                                                                                                           at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:180:21
                                                                                                 17:     0x564f91af488c - minesweep::ui::Ui::run::{{closure}}::h595609a4db8c04bd
                                                            at /tmp/minesweep-rs/src/ui.rs:405:45
                                                                                                   18:     0x564f91ae911e - ratatui::terminal::terminal::Terminal<B>::draw::h825abe5d67785dda
                                                                         at /home/sangge/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.0/src/terminal/terminal.rs:269:9
                                          19:     0x564f91afb23d - minesweep::ui::Ui::run::h60a5d2b60dea5845
                                                                                                                                           at /tmp/minesweep-rs/src/ui.rs:297:13
                               20:     0x564f91b0aeb6 - minesweep::main::h03cb40ce9f37713d
                                                                                                                         at /tmp/minesweep-rs/src/main.rs:42:5
             21:     0x564f91b00dbb - core::ops::function::FnOnce::call_once::h36aca94a98ddda6f
                                                                                                                              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
                                                                      22:     0x564f91b0baee - std::sys_common::backtrace::__rust_begin_short_backtrace::h4a600b0009aea02e
                                                      at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
      23:     0x564f91b1a3c1 - std::rt::lang_start::{{closure}}::h9ed3c6efb1352d9d
                                                                                                                 at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
                                               24:     0x564f91cfe490 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6abeee5a7794ceb5
                                                          at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
   25:     0x564f91cfe490 - std::panicking::try::do_call::hd6e966bb06877057
                                                                                                          at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
                                               26:     0x564f91cfe490 - std::panicking::try::hc9b3807f5768cb19
                                                                                                                                             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
                                                                                  27:     0x564f91cfe490 - std::panic::catch_unwind::h94a757c154076c6e
                                  at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
                                                                                                                      28:     0x564f91cfe490 - std::rt::lang_start_internal::{{closure}}::hc5223fb36050c743
                                                                                       at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
                     29:     0x564f91cfe490 - std::panicking::try::do_call::hddf7b4e1ebeb3f69
                                                                                                                            at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
                                                                 30:     0x564f91cfe490 - std::panicking::try::h1842860a1f941a31
                                                                                                                                                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
                                                                                                    31:     0x564f91cfe490 - std::panic::catch_unwind::h009016ccf811d4c3
                                                    at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
                                                                                                                                        32:     0x564f91cfe490 - std::rt::lang_start_internal::h3ed4fe7b2f419135
                                                                                            at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
                          33:     0x564f91b1a39a - std::rt::lang_start::hcc94c625d4a769ea
                                                                                                                        at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
                                                      34:     0x564f91b0bade - main
                                                                                     35:     0x7f30dd9afc8a - __libc_start_call_main
                                                                                                                                                                   at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
                                                                       36:     0x7f30dd9afd45 - __libc_start_main_impl
                                                                                                                                                     at ./csu/../csu/libc-start.c:360:3
                                      37:     0x564f91ac16b1 - _start
                                                                       38:                0x0 - <unknown>
                                                                                                         %                

My rustc version is 1.79.0

**Comment by Smart-SangGe** [comment]
I found binary created by cargo bulid --release is playable
